packages:
  - "apps/*"
  - "packages/*"

catalogs:
  default:
    dotenv: "^17.2.2"
    zod: "^4.1.13"
    typescript: "^5"
    "@types/node": "^22.13.14"
    "@cloudflare/workers-types": "^4.20251213.0"
    alchemy: "^0.82.1"
    "@libsql/client": "0.15.15"
    libsql: "0.5.22"
