export function getUsageText(): string {
	return [
		"Usage:",
		"  tsx src/cli.ts single  --seed 1 --maxTurns 200 --verbose --log --logFile ./match.json",
		"  tsx src/cli.ts single",
		"  tsx src/cli.ts replay  --logFile ./match.json",
		"  tsx src/cli.ts tourney --games 200 --seed 1 --maxTurns 200",
		"  tsx src/cli.ts mass    --games 10000 --parallel 4 --output ./results",
		"  tsx src/cli.ts analyze --input ./results [--json]",
		"  tsx src/cli.ts dashboard --input ./results --output ./dashboard.html",
		"  tsx src/cli.ts behavior --input ./results-or-artifacts --output ./behavior-metrics.json",
		"",
		"Engine options:",
		"  --turnLimit N       Engine turn limit (default: 40)",
		"  --actionsPerTurn N  Actions per turn (default: 7)",
		"  --boardColumns N    Board width: 17 or 21 (default: 17)",
		"  --scenario NAME     Combat scenario: melee, ranged, stronghold_rush, midfield, all_infantry, all_cavalry, all_archer, infantry_archer, cavalry_archer, infantry_cavalry, high_ground_clash, forest_chokepoints, resource_race",
		"  --invalidPolicy P   Invalid command policy: skip, stop_turn, forfeit",
		"  --moveValidationMode M  Move validation mode: strict, relaxed (default: strict)",
		"  --strict            Fail on harness divergence checks",
		"  --artifactDir PATH  Boardgame harness artifact output directory",
		"  --storeFullPrompt B Store full prompts in artifacts (true|false)",
		"  --storeFullOutput B Store full model output in artifacts (true|false)",
		"",
		"Bot options (for single, tourney, mass):",
		"  --bot1 TYPE    P1 bot type: random, greedy, aggressive, mockllm, llm (default: greedy)",
		"  --preset1 ID   Named hex_conquest preset for P1 (e.g., balanced_beta)",
		"  --bot2 TYPE    P2 bot type: random, greedy, aggressive, mockllm, llm (default: random)",
		"  --preset2 ID   Named hex_conquest preset for P2 (e.g., objective_beta)",
		'  --prompt1 TXT  Inline prompt for P1 mockllm/llm bot (e.g., "Always attack first")',
		'  --prompt2 TXT  Inline prompt for P2 mockllm/llm bot (e.g., "Defend and recruit")',
		"  --strategy1 S  MockLLM strategy: aggressive, defensive, random, strategic",
		"  --strategy2 S  MockLLM strategy: aggressive, defensive, random, strategic",
		"",
		"LLM options:",
		"  --model MODEL   Model id (alias: applies to both players if --model1/--model2 omitted)",
		"  --model1 MODEL  Model id for P1 (required when --bot1 llm)",
		"  --model2 MODEL  Model id for P2 (required when --bot2 llm)",
		"  --apiKey KEY    API key for provider (or set LLM_API_KEY env var)",
		"  --apiKey1 KEY   API key for P1 llm bot (overrides --apiKey)",
		"  --apiKey2 KEY   API key for P2 llm bot (overrides --apiKey)",
		"  --baseUrl URL   OpenAI-compatible base URL (default: OpenRouter)",
		"  --baseUrl1 URL  Base URL for P1 llm bot (overrides --baseUrl)",
		"  --baseUrl2 URL  Base URL for P2 llm bot (overrides --baseUrl)",
		"  --openrouterReferrer URL  Sets OpenRouter HTTP-Referer header (or OPENROUTER_REFERRER env var)",
		"  --openrouterTitle TXT     Sets OpenRouter X-Title header (or OPENROUTER_TITLE env var)",
		"  --llmDelay MS   Delay between LLM calls per bot (default: 0)",
		"  --llmParallelCalls N  Parallel API requests per LLM turn (default: 1)",
		"  --llmTimeoutMs MS     Per-call API timeout in ms (default: 35000)",
		"  --llmMaxRetries N     Max retry attempts per call (default: 3)",
		"  --llmRetryBaseMs MS   Retry backoff base delay in ms (default: 1000)",
		"  --llmMaxTokens N      Max output tokens per model call (default: 320)",
	].join("\n");
}
